# Bot configuration
TRADE_SYMBOL = 'ETHUSD'
TRADE_QUANTITY = 0.005
KLINE_INTERVAL = '3m'

# API keys (KEEP SECRET)
API_KEY = ''
API_SECRET = ''

# RSI config
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70.0
RSI_OVERSOLD = 30.0

